name: Build

on:
  push:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:

  Lint:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install flake8, etc
      run: |
        cd fastlmmclib
        pwd
        pip install flake8 pytest black isort --upgrade

    - name: Lint with flake8, etc
      run: |
        echo "flake8"
        flake8 .
        echo "black"
        black --version
        black --verbose --check .
        echo "isort"
        isort --check-only .

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        env:
          CIBW_BUILD: "cp3{9,10,11,12}-*"
          CIBW_SKIP: "*-win32 *i686 *ppc64le *s390x *universal2"
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: cd / && pytest {package}/tests/test.py
          CIBW_BUILD_VERBOSITY: 2

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

